version: 1

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    # You can also specify other tool versions:
    # nodejs: "20"
    # rust: "1.70"
    # golang: "1.20"

sphinx:
  configuration: docs/conf.py

formats: all

python:
  install:
    - requirements: docs/requirements.txt
